[package]
name = "rocket-web-server"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = {version = "0.5.1", features = ["json"] }
rusqlite = {version = "0.32.1", features = ["bundled"]}
serde = "1.0.210"
